set backspace=indent,eol,start
set splitbelow splitright
set background=dark
set termguicolors

syntax enable

au BufEnter todo.md setlocal foldminlines=0
au BufEnter todo.md setlocal foldmethod=indent
au VimEnter * ++nested colorscheme gruvbox

let g:netrw_liststyle = 3

" Plugins
call plug#begin()

Plug 'tpope/vim-surround'
Plug 'morhetz/gruvbox'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'yegappan/lsp'

call plug#end()

" Add and configure LSP servers
let lspServers = []
if has('unix')
	if executable('omnisharp')
		let lspServers += [#{name: 'omnisharp',
					\ filetype: 'cs',
					\ path: 'omnisharp',
					\ args: ['-z', '-lsp', '-e', 'utf-8']
					\}]
	endif
endif

autocmd User LspSetup call LspAddServer(lspServers)
