set backspace=indent,eol,start
set splitbelow splitright

syntax enable

au BufEnter todo.md setlocal foldminlines=0
au BufEnter todo.md setlocal foldmethod=indent

let g:netrw_liststyle = 3

" Plugins
call plug#begin()

Plug 'tpope/vim-surround'

call plug#end()
