set backspace=indent,eol,start
set splitbelow splitright
set background=dark
set autoindent

syntax enable

" Filetype-sepecific configurations
au Filetype cs setlocal tabstop=4 shiftwidth=0 expandtab

let g:netrw_liststyle = 3

" Plugins
call plug#begin()

Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'yegappan/lsp'

call plug#end()

" Add and configure LSP servers
let lspServers = []
if executable('omnisharp')
	let lspServers += [#{name: 'omnisharp',
				\ filetype: 'cs',
				\ path: 'omnisharp',
				\ args: ['-z', '-lsp', '-e', 'utf-8']
				\}]
endif

autocmd User LspSetup call LspAddServer(lspServers)

" Mappings

" LSP
let mapleader = ','

noremap <Leader>dd    :LspDiag current<CR>
noremap <Leader>ds    :LspDiag show<CR>
noremap <Leader>df    :LspDiag first<CR>
noremap <Leader>dn    :LspDiag next<CR>
noremap <Leader>dp    :LspDiag prev<CR>
noremap <Leader>h     :LspHover<CR>
noremap <Leader>ff    :LspFormat<CR>
noremap <Leader>fo    :LspFold<CR>
noremap <Leader><F2>  :LspRename<CR>
noremap <Leader><F12> :LspGotoDefinition<CR>

" Colors

if (has("termguicolors"))
	set termguicolors
endif
if &background == 'dark'
	highlight Normal guibg=#282828 guifg=#ebdbb2
	highlight NonText guifg=#504945
endif
